// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZ701DjCtqyx4QM67GJ7PxDHiaC_PvM0',
    appId: '1:364936943793:android:5fc8143e93a51fbf66aa90',
    messagingSenderId: '364936943793',
    projectId: 'erp-webstore',
    storageBucket: 'erp-webstore.firebasestorage.app',
    androidClientId: '364936943793-23b3ch1g19ioidbnnp2u2cn8ucl3c173.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlo_PG_6eGLl4_SEouTTukC5tD1qYrbkQ',
    appId: '1:364936943793:ios:46a418c8feb61da266aa90',
    messagingSenderId: '364936943793',
    projectId: 'erp-webstore',
    storageBucket: 'erp-webstore.firebasestorage.app',
    androidClientId: '364936943793-23b3ch1g19ioidbnnp2u2cn8ucl3c173.apps.googleusercontent.com',
    iosBundleId: 'com.eltarshopy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7YNQ58OlOZ-lMMLSkpFCpEvolgpWfQsc',
    appId: '1:364936943793:web:4bd3750c45676b6866aa90',
    messagingSenderId: '364936943793',
    projectId: 'erp-webstore',
    authDomain: 'erp-webstore.firebaseapp.com',
    storageBucket: 'erp-webstore.firebasestorage.app',
    measurementId: 'G-JEXL3XCR4T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlo_PG_6eGLl4_SEouTTukC5tD1qYrbkQ',
    appId: '1:364936943793:ios:06f2227bc221b8b366aa90',
    messagingSenderId: '364936943793',
    projectId: 'erp-webstore',
    storageBucket: 'erp-webstore.firebasestorage.app',
    androidClientId: '364936943793-23b3ch1g19ioidbnnp2u2cn8ucl3c173.apps.googleusercontent.com',
    iosBundleId: 'com.example.erp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7YNQ58OlOZ-lMMLSkpFCpEvolgpWfQsc',
    appId: '1:364936943793:web:a76cefef3725d4eb66aa90',
    messagingSenderId: '364936943793',
    projectId: 'erp-webstore',
    authDomain: 'erp-webstore.firebaseapp.com',
    storageBucket: 'erp-webstore.firebasestorage.app',
    measurementId: 'G-KYL46LKKFQ',
  );

}